name: identity_maker
description: "Student ID Designer - A Flutter application for designing and generating student identity cards"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluent_ui: ^4.9.0
  provider: ^6.1.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  pdf: ^3.10.7
  printing: ^5.12.0
  image: ^4.1.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/templates/
    - assets/fonts/
    - assets/localization/

  fonts:
    - family: NotoSansArabic
      fonts:
        - asset: assets/fonts/arabic/NotoSansArabic-Regular.ttf
        - asset: assets/fonts/arabic/NotoSansArabic-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/english/Roboto-Regular.ttf
        - asset: assets/fonts/english/Roboto-Bold.ttf
          weight: 700
